apps/devicedata/urls.py
from django.urls import path
from . import views


app_name = 'devicedata'

urlpatterns = [
    path('data/', views.view_data, name='view_data'),
    path('data_modified/', views.view_data_modified, name='view_data_modified'),
    path('data/devices/filtered/', views.filter_devices, name='filter_devices'),
    path('data/registers/filtered/', views.filter_registers, name='filter_registers'),
    path('data/filtered/', views.filter_data, name='filter_data'),
    path('data/filtered_modified/', views.filter_data_modified, name='filter_data_modified'),
    path('data/charts/', views.charts, name='charts_list'),
    path('data/charts/new/', views.chart_detail, name='chart_new'),
    path('data/charts/<int:chart_id>/', views.chart_detail, name='chart_detail'),
    path('data/charts/<int:chart_id>/delete/', views.chart_delete, name='chart_delete'),
    path('data/charts/<int:chart_id>/series/', views.chart_series_list, name='series_list'),
    path('data/charts/<int:chart_id>/series/new/', views.series_detail, name='series_new'),
    path('data/charts/<int:chart_id>/series/<int:series_id>/', views.series_detail, name='series_detail'),
    path('data/charts/<int:chart_id>/series/<int:series_id>/delete/', views.series_delete, name='series_delete'),
]

apps/devices/urls.py
from django.urls import path
from . import views


app_name = 'devices'

urlpatterns = [
    path('devices/', views.devices, name='devices'),
    path('devices/<int:device_id>/', views.device_detail, name='device_detail'),
    path('devices/<int:device_id>/delete/', views.device_delete, name='device_delete'),
    path('devices/new/', views.device_detail, name='device_detail_new'),
    path('devicetypes/', views.device_types, name='device_types'),
    path('devicetypes/<int:device_type_id>/', views.device_type_detail, name='device_type_detail'),
    path('devicetypes/<int:device_type_id>/delete/', views.device_type_delete, name='device_type_delete'),
    path('devicetypes/new/', views.device_type_detail, name='device_type_detail_new'),
    path('devicetypes/<int:device_type_id>/registers/', views.device_type_registers, name='device_type_registers'),
    path('devicetypes/<int:device_type_id>/registers/<int:register_id>/', views.device_type_register_detail,
         name='device_type_register_detail'),
    path('devicetypes/<int:device_type_id>/registers/<int:register_id>/delete/', views.device_type_register_delete,
         name='device_type_register_delete'),
    path('devicetypes/<int:device_type_id>/registers/new/', views.device_type_register_detail,
         name='device_type_register_detail_new'),
    path('devices/<int:device_id>/registers/', views.device_registers,
         name='device_registers'),
]

modbus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('devices/', include('apps.devices.urls')),
]

urlpatterns += [
    path('', include('apps.ports.urls')),
]

urlpatterns += [
    path('tasks/', include('apps.tasks.urls')),
]

urlpatterns += [
    path('', include('apps.devicedata.urls')),
]

urlpatterns += [
    path('', views.main, name='main'),
    path('devices_scheme/filtered', views.filter_devices_scheme, name='filter_devices_scheme'),
    path('devices_scheme/update', views.update_devices_scheme, name='update_devices_scheme'),
    path('errors/list', views.errors_list, name='errors_list'),
]

urlpatterns += [
    path('', RedirectView.as_view(url='/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/devicedata/models.py
from django.db import models
from apps.devices.models import Device, DeviceTypeRegister


class ChartUnit(models.Model):
    u"""
    Saved prepared graph units to show with charts or tables device registers data
    """
    name = models.CharField(
        u'chart name',
        max_length=50,
        blank=False, null=False, unique=True
    )

    description = models.TextField(
        u'description of chart unit',
        max_length=300,
        blank=True, null=True
    )

    class Meta:
        verbose_name = u'chart unit'
        verbose_name_plural = u'chart units'
        db_table = 'poll_chart_units'

    def __str__(self):
        return u'{0}'.format(self.name)


class ChartContent(models.Model):
    u"""
    Chart contents
    """
    chart = models.ForeignKey(
        'ChartUnit', verbose_name=u'Chart unit', on_delete=models.CASCADE
    )

    device = models.ForeignKey(
        'devices.Device', verbose_name=u'Device', on_delete=models.CASCADE
    )

    register = models.ForeignKey(
        'devices.DeviceTypeRegister', verbose_name=u'Device register', on_delete=models.CASCADE
    )

    additive = models.FloatField(
        u'additive modifier',
        blank=True, null=True, default=0
    )

    coefficient = models.FloatField(
        u'coefficient modifier',
        blank=True, null=True, default=1
    )

    check_mask = models.PositiveIntegerField(
        u'check logical equality with mask, bool(x & mask), if true => alert',
        help_text=u'positive integer value',
        blank=True, null=True
    )

    name = models.CharField(
        u'chart element name',
        max_length=60,
        help_text=u'chart element name',
        blank=True, null=True
    )

    class Meta:
        verbose_name = u'chart content'
        verbose_name_plural = u'chart contents'
        db_table = 'poll_chart_contents'

    def __str__(self):
        if self.name:
            return u'{0}'.format(self.name)
        else:
            return u'{0}-{1} [{2};{3};{4}]'.format(self.device.name, self.register.name,
                                                   self.additive, self.coefficient, self.check_mask)

apps/tasks/models.py
from django.db import models
from apps.common.base_enum import BaseEnumerate


class ErrorReportPlans(BaseEnumerate):
    u"""
    Plans of error reporting
    """

    (
        DONT_REPORT, REPORT_ALL, REPORT_DB, REPORT_LOG
    ) = range(4)

    values = {
        DONT_REPORT: u'Dont report errors',
        REPORT_ALL: u'Report errors in DB and logs',
        REPORT_DB: u'Report errors in DB',
        REPORT_LOG: u'Report errors in logs'
    }


class ReadTaskStatus(BaseEnumerate):
    u"""
    Task status: enabled/disabled
    """

    (
        ENABLED, DISABLED
    ) = range(2)

    values = {
        ENABLED: u'Task is enabled',
        DISABLED: u'Task is disabled'
    }


class WriteTaskStatus(BaseEnumerate):
    u"""
    Task status: enabled/disabled
    """

    (
        ENABLED, DISABLED, SUCCESS, ERROR
    ) = range(4)

    values = {
        ENABLED: u'Task is enabled',
        DISABLED: u'Task is disabled',
        SUCCESS: u'Task has successful result',
        ERROR: u'Task is finished with errors'
    }


class ReadTask(models.Model):
    u"""
    Task to read specific register from some device
    """

    device = models.OneToOneField(
        'devices.Device', verbose_name=u'Device', on_delete=models.CASCADE
    )

    interval = models.PositiveIntegerField(
        u'polling period, s',
        default=60,
        help_text=u'seconds',
        blank=False, null=False
    )

    data_miss_error_report = models.PositiveIntegerField(
        u'report plan on missing data error',
        choices=ErrorReportPlans.get_choices(),
        default=ErrorReportPlans.REPORT_LOG
    )

    status = models.PositiveIntegerField(
        u'task status',
        choices=ReadTaskStatus.get_choices(),
        default=ReadTaskStatus.DISABLED
    )

    class Meta:
        verbose_name = u'read task'
        verbose_name_plural = u'read tasks'
        ordering = ['device']
        db_table = 'poll_read_tasks'

    def __str__(self):
        return u'{0} read task'.format(self.device.name)


class WriteTask(models.Model):
    u"""
    Task to write specific register to some device
    """

    device = models.ForeignKey(
        'devices.Device', verbose_name=u'Device', on_delete=models.CASCADE
    )

    register = models.ForeignKey(
        'devices.DeviceTypeRegister', verbose_name=u'Register', on_delete=models.CASCADE
    )

    value = models.CharField(
        u'value to set to register',
        max_length=20,
        help_text=u'String representation! Be cautious!',
        blank=False, null=False
    )

    status = models.PositiveIntegerField(
        u'task status',
        choices=WriteTaskStatus.get_choices(),
        default=WriteTaskStatus.DISABLED
    )

    changed_datetime = models.DateTimeField(
        u'time point of last modification',
        auto_now=True
    )

    class Meta:
        verbose_name = u'write task'
        verbose_name_plural = u'write tasks'
        ordering = ['device', 'register']
        db_table = 'poll_write_tasks'

    def __str__(self):
        return u'Write task {0} register {1} value {2}'.format(self.device.name, self.register.name, self.value)


class Threshold(models.Model):
    u"""
    Threshold for some device register, used to track by task
    """

    task = models.ForeignKey(
        'ReadTask', verbose_name=u'Task', on_delete=models.CASCADE
    )

    register = models.ForeignKey(
        'devices.DeviceTypeRegister', verbose_name=u'Register', on_delete=models.CASCADE
    )

    # FloatField instead of DecimalField because of firebird problems
    low_threshold = models.FloatField(
        u'low threshold',
        blank=True, null=True
    )

    # FloatField instead of DecimalField because of firebird problems
    high_threshold = models.FloatField(
        u'high threshold',
        blank=True, null=True
    )

    additive = models.FloatField(
        u'additive modifier',
        blank=True, null=True, default=0
    )

    coefficient = models.FloatField(
        u'coefficient modifier',
        blank=True, null=True, default=1
    )

    check_mask = models.PositiveIntegerField(
        u'check logical equality with mask, bool(x & mask), if true => alert',
        help_text=u'positive integer value',
        blank=True, null=True
    )

    mask_explain = models.CharField(
        u'explanation of mask check',
        max_length=30,
        help_text=u'explanation of mask check (for alert message)',
        blank=True, null=True
    )

    threshold_error_report = models.PositiveIntegerField(
        u'report plan on threshold error',
        choices=ErrorReportPlans.get_choices(),
        default=ErrorReportPlans.REPORT_LOG
    )

    class Meta:
        verbose_name = u'threshold'
        verbose_name_plural = u'thresholds'
        # unique_together = ('task', 'register')
        ordering = ['task', 'register']
        db_table = 'poll_thresholds'

    def __str__(self):
        return u'Threshold of {0} register {1}'.format(self.task.device.name, self.register.name)

apps/devicedata/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import ChartUnit, ChartContent
from apps.devices.models import DeviceTypeRegister


class ChartUnitForm(forms.ModelForm):
    class Meta:
        model = ChartUnit
        fields = ['name', 'description']


class ChartContentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ChartContentForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance:
            self.fields['chart'].widget.attrs['hidden'] = True
            self.fields['chart'].label = ''

    def clean_chart(self):
        instance = getattr(self, 'instance', None)
        if instance:
            return instance.chart
        else:
            return self.cleaned_data['chart']

    def clean(self):
        cleaned_data = super().clean()
        device = cleaned_data.get("device")
        register = cleaned_data.get("register")

        if device and register:
            if len(list(DeviceTypeRegister.objects.filter(device_type__device__id=device.id, id=register.id))) == 0:
                raise ValidationError('Register does not belong to this device')

    class Meta:
        model = ChartContent
        fields = ['chart', 'name', 'device', 'register', 'additive', 'coefficient', 'check_mask']

templates/devicedata/chart_detail.html
{% extends "base_site.html" %}
{% block content %}

<div class="page-title-holder d-flex align-items-center">
    <h1 class="page-title">
        {% if chart.id %}
            {{ chart_title }}
        {% else %}
            New chart
        {% endif %}
    </h1>
</div>
<div class="d-flex align-items-start justify-content-between">
    <div class="d-flex col-8">
        <form class="detail-form col-10" action="" method="post">
        {% csrf_token %}
            {% if form.errors %}
            {% for error in form.non_field_errors %}
                <br>
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endfor %}
            {% endif %}
            {% for field in form %}
                {% if field.errors %}
                    <div class="form-group detail-form-group">
                        <label class="">{{ field.label }}</label>
                        <div class="detail-form-control">{{ field }}</div>
                        {% for error in field.errors %}
                            <div class="alert alert-danger" role="alert">
                                {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    <div class="form-group detail-form-group">
                        <label class="form-text">{{ field.label }}</label>
                        <div class="detail-form-control">{{ field }}</div>
                        {% if field.help_text %}
                            <p class="form-text"><small>{{ field.help_text }}</small></p>
                        {% endif %}
                    </div>
                {% endif %}
            {% endfor %}
            <div class="form-group col-8 detail-form-group">
                <button type="submit" class="btn btn-primary" >Save chart</button>
                <a class="btn btn-secondary" href="{% url 'devicedata:charts_list' %}">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

{% block extrajs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#navbarNav li').removeClass('active')
        $('#navbarNav li:nth-child(3)').toggleClass('active')

        let elements = document.querySelectorAll('div.detail-form-control > :first-child')
        elements.forEach(el => el.classList.add("form-control"))
    </script>
{% endblock extrajs %}

templates/devicedata/charts_list.html
{% extends "base_site.html" %}
{% block content %}

<div class="page-title-holder d-flex align-items-center">
    <h1 class="page-title">Charts<span class="badge badge-light">{{ charts|length }}</span></h1>

    <div class="page-title-controls">
        <a class="btn btn-success" href="{% url 'devicedata:chart_new' %}">New chart</a>
    </div>
</div>

<div >
{% if charts %}
    <ul class="objects-list">
    {% for chart in charts %}
        <li class="objects-row d-flex">
            <div class="object-details d-sm-flex flex-sm-fill align-items-center justify-content-between">
                <div class="d-flex">
                    <div class="d-flex align-items-center object-title">
                        <a href="{% url 'devicedata:chart_detail' chart.id %}">{{ chart.name }}</a>
                    </div>
                </div>
                <div class="d-flex">
                    <div class="d-flex align-items-center object-title">
                        <a href="{% url 'devicedata:series_list' chart.id %}">Series</a>
                    </div>
                </div>
                <div class="object-description d-flex flex-sm-column align-items-center align-items-sm-start flex-wrap">
                    <p dir="auto">Description: {{ chart.description }}</p>
                </div>
                <div class="d-flex align-items-center align-items-sm-end flex-shrink-0 text-secondary objects-list-controls">
                    <a class="btn btn-info" href="{% url 'devicedata:chart_detail' chart.id %}" title="Edit"><i class="fas fa-edit"></i></a>
                    <a>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal" data-id="{{ chart.id }}" data-name="{{ chart.name }}" title="Delete">
                            <i class="fas fa-trash-alt"></i>
                        </button>
                    </a>
                </div>
            </div>
        </li>
    {% endfor %}
    </ul>
{% endif %}
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete object alert</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <p>You are going to delete</p>
            <p class="modal-body-detail"></p>
        </div>
        <div class="modal-footer">
            <a class="btn btn-secondary" data-dismiss="modal">Cancel</a>
            <a class="btn btn-primary confirm-delete" href="">Delete</a>
        </div>
        </div>
    </div>
</div>

{% endblock content %}


{% block extrajs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#navbarNav li').removeClass('active')
        $('#navbarNav li:nth-child(3)').toggleClass('active')

        $('#deleteModal').on('show.bs.modal', function (event) {
            let button = $(event.relatedTarget) // Button that triggered the modal
            let object_name = button.data('name') // Extract info from data-* attributes
            let object_id = button.data('id') // Extract info from data-* attributes
            let modal = $(this)
            modal.find('p.modal-body-detail').text(object_name)
            modal.find('a.confirm-delete').attr("href", "{% url 'devicedata:charts_list' %}" + object_id + "/delete/")
        })
    </script>
{% endblock extrajs %}

templates/devicedata/series_detail.html
{% extends "base_site.html" %}
{% block content %}

<div class="page-title-holder d-flex align-items-center">
    <h1 class="page-title">
        <a href="{% url 'devicedata:chart_detail' series.chart.id %}">{{ series.chart.name }} </a>
        {% if series.id %}
            {{ series_title }}
        {% else %}
            New series
        {% endif %}
    </h1>
</div>
<div class="d-flex align-items-start justify-content-between">
    <div class="d-flex col-8">
        <form class="detail-form col-10" action="" method="post">
        {% csrf_token %}
            {% if form.errors %}
            {% for error in form.non_field_errors %}
                <br>
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endfor %}
            {% endif %}
            {% for field in form %}
                {% if field.errors %}
                    <div class="form-group detail-form-group">
                        <label class="">{{ field.label }}</label>
                        <div class="detail-form-control">{{ field }}</div>
                        {% for error in field.errors %}
                            <div class="alert alert-danger" role="alert">
                                {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    <div class="form-group detail-form-group">
                        <label class="form-text">{{ field.label }}</label>
                        <div class="detail-form-control">{{ field }}</div>
                        {% if field.help_text %}
                            <p class="form-text"><small>{{ field.help_text }}</small></p>
                        {% endif %}
                    </div>
                {% endif %}
            {% endfor %}
            <div class="form-group col-8 detail-form-group">
                <button type="submit" class="btn btn-primary" >Save series</button>
                <a class="btn btn-secondary" href="{% url 'devicedata:series_list' series.chart.id %}">Cancel</a>
            </div>
        </form>
    </div>
{##}
{#    <div class="d-flex col-md-4 col-4 align-items-start flex-column">#}
{#        <div class="detail-additional-list-title">#}
{#            <h2 class="page-title">#}
{#                <a href="#{{ device.readtask_set.first.id }}">#}
{#                    Read Task#}
{#                </a>#}
{#            </h2>#}
{#        </div>#}
{#        <div class="detail-additional-list-title">#}
{#            <h2 class="page-title">#}
{#                <a data-toggle="collapse" href="#collapseDetailList" role="button" aria-expanded="false" aria-controls="collapseDetailList">#}
{#                    Write tasks <span class="badge badge-light">{{ device.writetask_set.all|length }}</span>#}
{#                </a>#}
{#            </h2>#}
{#        </div>#}
{#        <div class="">#}
{#            <div class="collapse" id="collapseDetailList">#}
{#                <ul class="detail-additional-list">#}
{#                {% for task in device.writetask_set.all %}#}
{#                    <li class="">#}
{#                        <div>#}
{#                            <h5>#}
{#                                <a href="#{{ task.id }}">{{ task.register.name }} / {{ task.value }}</a>#}
{#                            </h5>#}
{#                        </div>#}
{#                    </li>#}
{#                {% endfor %}#}
{#                </ul>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{##}
</div>
{% endblock content %}

{% block extrajs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#navbarNav li').removeClass('active')
        $('#navbarNav li:nth-child(3)').toggleClass('active')

        let elements = document.querySelectorAll('div.detail-form-control > :first-child')
        elements.forEach(el => el.classList.add("form-control"))

        $('#id_device').on('change', getRegisters)
        $('form').onload = getRegisters()

        function getRegisters() {
            let device_id = document.querySelector('#id_device option:checked').getAttribute("value")
            if (!device_id) {
                device_id = 0
            }
            // get registers of device type and edit select of register
            $.getJSON("{% url 'devices:devices' %}" + device_id + "/registers/", function(data) {
                let active_option_value = document.querySelector('#id_register option:checked').getAttribute("value")
                let registers_select = document.querySelector('#id_register')
                registers_select.innerHTML = ''
                let option = document.createElement("option")
                option.innerHTML = "---------"
                option.setAttribute("value", '')
                registers_select.appendChild(option)

                if (data['registers']) {
                    data['registers'].forEach((currentValue) => {
                        let option = document.createElement("option")
                        option.setAttribute("value", currentValue['id'])
                        option.innerHTML = currentValue['value']
                        registers_select.appendChild(option)
                    })
                }

                if (active_option_value) {
                    let active_option = document.querySelector('#id_register option[value="' + active_option_value + '"]')
                    if (active_option) {
                        active_option.setAttribute("selected", '')
                    }
                }
            })
        }
    </script>
{% endblock extrajs %}

templates/devicedata/series_list.html
{% extends "base_site.html" %}
{% block content %}

<div class="page-title-holder d-flex align-items-center">
    <h1 class="page-title"><a href="{% url 'devicedata:chart_detail' chart.id %}">{{ chart }}</a> series <span class="badge badge-light">{{ series_list|length }}</span></h1>

    <div class="page-title-controls">
        <a class="btn btn-success" href="{% url 'devicedata:series_new' chart.id %}">New series</a>
    </div>
</div>

<div >
{% if series_list %}
    <ul class="objects-list">
    {% for series in series_list %}
        <li class="objects-row d-flex">
            <div class="object-details d-sm-flex flex-sm-fill align-items-center justify-content-between">
                <div class="d-flex">
                    <div class="d-flex align-items-center object-title">
                        <p dir="auto">
                            <a href="{% url 'devicedata:series_detail' chart.id series.id %}"><strong>{{ series.name }}</strong></a>
                        </p>
                    </div>
                </div>
                <div class="object-description d-flex flex-sm-column align-items-end align-items-sm-start flex-wrap">
                    <p dir="auto">Device: <strong>{{ series.device.name }}</strong></p>
                    <p dir="auto">Register: {{ series.register.name }}</p>
                </div>
                <div class="object-description d-flex flex-sm-column align-items-end align-items-sm-start flex-wrap">
                    <p dir="auto">Additive: {{ series.additive }}</p>
                    <p dir="auto">Coefficient: {{ series.coefficient }}</p>
                    <p dir="auto">Mask: {{ series.check_mask }}</p>
                </div>
                <div class="d-flex align-items-center align-items-sm-end flex-shrink-0 text-secondary objects-list-controls">
                    <a class="btn btn-info" href="{% url 'devicedata:series_detail' chart.id series.id %}" title="Edit"><i class="fas fa-edit"></i></a>
                    <a>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal" data-id="{{ series.id }}" data-name="{{ series.name }}" title="Delete">
                            <i class="fas fa-trash-alt"></i>
                        </button>
                    </a>
                </div>
            </div>
        </li>
    {% endfor %}
    </ul>
{% endif %}
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete object alert</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <p>You are going to delete</p>
            <p class="modal-body-detail"></p>
        </div>
        <div class="modal-footer">
            <a class="btn btn-secondary" data-dismiss="modal">Cancel</a>
            <a class="btn btn-primary confirm-delete" href="">Delete</a>
        </div>
        </div>
    </div>
</div>

{% endblock content %}


{% block extrajs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#navbarNav li').removeClass('active')
        $('#navbarNav li:nth-child(3)').toggleClass('active')

        $('#deleteModal').on('show.bs.modal', function (event) {
            let button = $(event.relatedTarget) // Button that triggered the modal
            let object_name = button.data('name') // Extract info from data-* attributes
            let object_id = button.data('id') // Extract info from data-* attributes
            let modal = $(this)
            modal.find('p.modal-body-detail').text(object_name)
            modal.find('a.confirm-delete').attr("href", "{% url 'devicedata:series_list' chart.id %}" + object_id + "/delete/")
        })
    </script>
{% endblock extrajs %}