apps/devicedata/urls.py
from django.urls import path
from . import views


app_name = 'devicedata'

urlpatterns = [
    path('data/', views.view_data, name='view_data'),
    path('data_modified/', views.view_data_modified, name='view_data_modified'),
    path('data/devices/filtered/', views.filter_devices, name='filter_devices'),
    path('data/registers/filtered/', views.filter_registers, name='filter_registers'),
    path('data/filtered/', views.filter_data, name='filter_data'),
    path('data/filtered_modified/', views.filter_data_modified, name='filter_data_modified'),
    path('data/charts/', views.charts, name='charts_list'),
    path('data/charts/new/', views.chart_detail, name='chart_new'),
    path('data/charts/<int:chart_id>/', views.chart_detail, name='chart_detail'),
    path('data/charts/<int:chart_id>/delete/', views.chart_delete, name='chart_delete'),
    path('data/charts/<int:chart_id>/series/', views.chart_series_list, name='series_list'),
    path('data/charts/<int:chart_id>/series/new/', views.series_detail, name='series_new'),
    path('data/charts/<int:chart_id>/series/<int:series_id>/', views.series_detail, name='series_detail'),
    path('data/charts/<int:chart_id>/series/<int:series_id>/delete/', views.series_delete, name='series_delete'),
]

apps/devices/urls.py
from django.urls import path
from . import views


app_name = 'devices'

urlpatterns = [
    path('devices/', views.devices, name='devices'),
    path('devices/<int:device_id>/', views.device_detail, name='device_detail'),
    path('devices/<int:device_id>/delete/', views.device_delete, name='device_delete'),
    path('devices/new/', views.device_detail, name='device_detail_new'),
    path('devicetypes/', views.device_types, name='device_types'),
    path('devicetypes/<int:device_type_id>/', views.device_type_detail, name='device_type_detail'),
    path('devicetypes/<int:device_type_id>/delete/', views.device_type_delete, name='device_type_delete'),
    path('devicetypes/new/', views.device_type_detail, name='device_type_detail_new'),
    path('devicetypes/<int:device_type_id>/registers/', views.device_type_registers, name='device_type_registers'),
    path('devicetypes/<int:device_type_id>/registers/<int:register_id>/', views.device_type_register_detail,
         name='device_type_register_detail'),
    path('devicetypes/<int:device_type_id>/registers/<int:register_id>/delete/', views.device_type_register_delete,
         name='device_type_register_delete'),
    path('devicetypes/<int:device_type_id>/registers/new/', views.device_type_register_detail,
         name='device_type_register_detail_new'),
    path('devices/<int:device_id>/registers/', views.device_registers,
         name='device_registers'),
]

apps/ports/urls.py
from django.urls import path
from . import views


app_name = 'ports'

urlpatterns = [
    path('ports/', views.ports, name='ports'),
    path('ports/<int:port_id>/', views.port_detail, name='port_detail'),
    path('ports/new/', views.port_detail, name='port_detail_new'),
    path('ports/<int:port_id>/delete/', views.port_delete, name='port_delete'),
]

apps/tasks/urls.py
from django.urls import path
from . import views


app_name = 'tasks'

urlpatterns = [
    path('readtasks/', views.read_tasks, name='read_tasks'),
    path('readtasks/<int:task_id>/', views.read_task_detail, name='read_task_detail'),
    path('readtasks/<int:task_id>/delete/', views.read_task_delete, name='read_task_delete'),
    path('readtasks/new/', views.read_task_detail, name='read_task_detail_new'),
    path('readtasks/<int:task_id>/thresholds/', views.task_thresholds, name='task_thresholds'),
    path('readtasks/<int:task_id>/thresholds/<int:threshold_id>/', views.task_threshold_detail,
         name='task_threshold_detail'),
    path('readtasks/<int:task_id>/thresholds/<int:threshold_id>/delete/', views.task_threshold_delete,
         name='task_threshold_delete'),
    path('readtasks/<int:task_id>/thresholds/new/', views.task_threshold_detail, name='task_threshold_detail_new'),
    path('writetasks/', views.write_tasks, name='write_tasks'),
    path('writetasks/<int:task_id>/', views.write_task_detail, name='write_task_detail'),
    path('writetasks/<int:task_id>/delete/', views.write_task_delete, name='write_task_delete'),
    path('writetasks/new/', views.write_task_detail, name='write_task_detail_new'),

    path('readtasks/<int:task_id>/toggle/', views.read_task_toggle, name='read_task_toggle'),
    path('writetasks/<int:task_id>/toggle/', views.write_task_toggle, name='write_task_toggle'),
]

modbus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('devices/', include('apps.devices.urls')),
]

urlpatterns += [
    path('', include('apps.ports.urls')),
]

urlpatterns += [
    path('tasks/', include('apps.tasks.urls')),
]

urlpatterns += [
    path('', include('apps.devicedata.urls')),
]

urlpatterns += [
    path('', views.main, name='main'),
    path('devices_scheme/filtered', views.filter_devices_scheme, name='filter_devices_scheme'),
    path('devices_scheme/update', views.update_devices_scheme, name='update_devices_scheme'),
    path('errors/list', views.errors_list, name='errors_list'),
]

urlpatterns += [
    path('', RedirectView.as_view(url='/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base_site.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
    {% block title %}
        Modbus logger
    {% endblock title %}
    </title>

    {% block extrahead %}
    {% endblock extrahead %}

    {% load static %}
    <script type="text/javascript" src="{% static 'js/jquery-3.5.1.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/js.cookie.js' %}"></script>
    <link rel="stylesheet" href="{% static 'bootstrap-4.6.0/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'fa/css/all.css' %}">
    <link rel="icon" href="{% static 'image/favicon.png' %}">
    <link rel="shortcut icon" href="{% static 'image/favicon.ico' %}">
    <script type="text/javascript" src="{% static 'bootstrap-4.6.0/js/bootstrap.js' %}"></script>
    {% block extrastyle %}
    {% endblock extrastyle %}

    {% block header %}
        <nav class="navbar sticky-top navbar-expand-sm navbar-dark" style="background-color: #ffa04d;">
            <a class="navbar-brand h1" href="/">
                <img src="{% static 'image/logo.svg' %}" alt="Логотип" width="30" height="30" class="d-inline-block align-top">
                DLeader
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link h5" href="/">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link h5" href="{% url 'ports:ports' %}">Ports</a>
                    </li>
                    <li class="nav-item h5 dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDevicesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Devices
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDevicesDropdown">
                            <a class="dropdown-item" href="{% url 'devices:device_types' %}">Devices types</a>
                            <a class="dropdown-item" href="{% url 'devices:devices' %}">Devices</a>
                        </div>
                    </li>
                    <li class="nav-item h5 dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDataDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Data
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDataDropdown">
                            <a class="dropdown-item" href="{% url 'devicedata:charts_list' %}">Charts</a>
                            <a class="dropdown-item" href="{% url 'devicedata:view_data' %}">Data old</a>
                            <a class="dropdown-item" href="{% url 'devicedata:view_data_modified' %}">Data modified</a>
                        </div>
                    </li>
                    <li class="nav-item h5 dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarTasksDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Tasks
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarTasksDropdown">
                            <a class="dropdown-item" href="{% url 'tasks:read_tasks' %}">Read tasks</a>
                            <a class="dropdown-item" href="{% url 'tasks:write_tasks' %}">Write tasks</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    {% endblock header %}
</head>
<body>
    <div class="container-fluid">
        <div class="">
        {% block bodyheader %}
        {% endblock bodyheader %}

        {% block sidebar %}
        {% endblock sidebar %}

        {% block content %}
        {% endblock content %}
        </div>
    </div>
</body>
{% block footer %}
{% endblock footer %}

{% block extrajs %}
{% endblock extrajs %}

</html>