apps/devices/urls.py
from django.urls import path
from . import views


app_name = 'devices'

urlpatterns = [
    path('devices/', views.devices, name='devices'),
    path('devices/<int:device_id>/', views.device_detail, name='device_detail'),
    path('devices/<int:device_id>/delete/', views.device_delete, name='device_delete'),
    path('devices/new/', views.device_detail, name='device_detail_new'),
    path('devicetypes/', views.device_types, name='device_types'),
    path('devicetypes/<int:device_type_id>/', views.device_type_detail, name='device_type_detail'),
    path('devicetypes/<int:device_type_id>/delete/', views.device_type_delete, name='device_type_delete'),
    path('devicetypes/new/', views.device_type_detail, name='device_type_detail_new'),
    path('devicetypes/<int:device_type_id>/registers/', views.device_type_registers, name='device_type_registers'),
    path('devicetypes/<int:device_type_id>/registers/<int:register_id>/', views.device_type_register_detail,
         name='device_type_register_detail'),
    path('devicetypes/<int:device_type_id>/registers/<int:register_id>/delete/', views.device_type_register_delete,
         name='device_type_register_delete'),
    path('devicetypes/<int:device_type_id>/registers/new/', views.device_type_register_detail,
         name='device_type_register_detail_new'),
    path('devices/<int:device_id>/registers/', views.device_registers,
         name='device_registers'),
]

apps/ports/urls.py
from django.urls import path
from . import views


app_name = 'ports'

urlpatterns = [
    path('ports/', views.ports, name='ports'),
    path('ports/<int:port_id>/', views.port_detail, name='port_detail'),
    path('ports/new/', views.port_detail, name='port_detail_new'),
    path('ports/<int:port_id>/delete/', views.port_delete, name='port_delete'),
]

apps/tasks/urls.py
from django.urls import path
from . import views


app_name = 'tasks'

urlpatterns = [
    path('readtasks/', views.read_tasks, name='read_tasks'),
    path('readtasks/<int:task_id>/', views.read_task_detail, name='read_task_detail'),
    path('readtasks/<int:task_id>/delete/', views.read_task_delete, name='read_task_delete'),
    path('readtasks/new/', views.read_task_detail, name='read_task_detail_new'),
    path('readtasks/<int:task_id>/thresholds/', views.task_thresholds, name='task_thresholds'),
    path('readtasks/<int:task_id>/thresholds/<int:threshold_id>/', views.task_threshold_detail,
         name='task_threshold_detail'),
    path('readtasks/<int:task_id>/thresholds/<int:threshold_id>/delete/', views.task_threshold_delete,
         name='task_threshold_delete'),
    path('readtasks/<int:task_id>/thresholds/new/', views.task_threshold_detail, name='task_threshold_detail_new'),
    path('writetasks/', views.write_tasks, name='write_tasks'),
    path('writetasks/<int:task_id>/', views.write_task_detail, name='write_task_detail'),
    path('writetasks/<int:task_id>/delete/', views.write_task_delete, name='write_task_delete'),
    path('writetasks/new/', views.write_task_detail, name='write_task_detail_new'),

    path('readtasks/<int:task_id>/toggle/', views.read_task_toggle, name='read_task_toggle'),
    path('writetasks/<int:task_id>/toggle/', views.write_task_toggle, name='write_task_toggle'),
]

modbus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('devices/', include('apps.devices.urls')),
]

urlpatterns += [
    path('', include('apps.ports.urls')),
]

urlpatterns += [
    path('tasks/', include('apps.tasks.urls')),
]

urlpatterns += [
    path('', include('apps.devicedata.urls')),
]

urlpatterns += [
    path('', views.main, name='main'),
    path('devices_scheme/filtered', views.filter_devices_scheme, name='filter_devices_scheme'),
    path('devices_scheme/update', views.update_devices_scheme, name='update_devices_scheme'),
    path('errors/list', views.errors_list, name='errors_list'),
]

urlpatterns += [
    path('', RedirectView.as_view(url='/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/devices/models.py
from django.db import models
from apps.common.base_enum import BaseEnumerate
from apps.ports.models import Port
from apps.tasks.models import ErrorReportPlans


class RecordTypes(BaseEnumerate):
    u"""
    Explains how to record data from devices
    """

    (
        DONT_RECORD, DB_RECORD, FILE_RECORD
    ) = range(3)

    values = {
        DONT_RECORD: u'Dont record data from device',
        DB_RECORD: u'Save data from device into database',
        FILE_RECORD: u'Save data from device into file'
    }


class GlobalReportingStatus(BaseEnumerate):
    u"""
    Reporting errors status
    """

    (
        DONT_REPORT, REPORT
    ) = range(2)

    values = {
        DONT_REPORT: u'Disable global device error reporting',
        REPORT: u'Enable global device error reporting'
    }


class ReadFunctionCodes(BaseEnumerate):
    u"""
    Function codes for read register procedures
    """
    NO_READ = 0
    READ_COIL_STATUS = 1
    READ_DISCRETE_INPUTS = 2
    READ_HOLDING_REGISTERS = 3
    READ_INPUT_REGISTERS = 4

    values = {
        NO_READ: u'no read function (0)',
        READ_COIL_STATUS: u'read coil status (1)',
        READ_DISCRETE_INPUTS: u'read discrete inputs (2)',
        READ_HOLDING_REGISTERS: u'read holding registers (3)',
        READ_INPUT_REGISTERS: u'read input registers (4)'
    }


class WriteFunctionCodes(BaseEnumerate):
    u"""
    Function codes for write register procedures
    """
    NO_WRITE = 0
    FORCE_SINGLE_COIL = 5
    PRESET_SINGLE_REGISTER = 6
    FORCE_MULTIPLE_COILS = 15
    PRESET_MULTIPLE_REGISTERS = 16

    values = {
        NO_WRITE: u'no write function (0)',
        FORCE_SINGLE_COIL: u'write single coil (5)',
        PRESET_SINGLE_REGISTER: u'write single register (6)',
        FORCE_MULTIPLE_COILS: u'write multiple coils (15)',
        PRESET_MULTIPLE_REGISTERS: u'write multiple registers (16)'
    }


class RegisterDataType(BaseEnumerate):
    u"""
    Data types of device registers
    """
    INTEGER = 2
    INT4 = 3
    FLOAT = 4

    values = {
        INTEGER: u'integer (2 byte)',
        INT4: u'integer (4 byte)',
        FLOAT: u'float (4 byte)'
    }


class DeviceType(models.Model):
    u"""
    Device type, needed for united storing data from devices of the same type
    """

    name = models.CharField(
        u'device type name',
        max_length=100,
        blank=False, null=False, unique=True
    )

    table_name = models.CharField(
        u'device data destination (e.g. table name, folder name...)',
        max_length=25,
        blank=False, null=False, unique=True
    )

    comment = models.TextField(
        u'additional comment',
        max_length=1000,
        blank=True, null=True
    )

    class Meta:
        verbose_name = u'device type'
        verbose_name_plural = u'device types'
        ordering = ['name']
        db_table = 'poll_device_types'

    def __str__(self):
        return u'{0}'.format(self.name)


class Device(models.Model):
    u"""
    Device to poll data from
    """
    name = models.CharField(
        u'device name',
        max_length=25,
        blank=False, null=False, unique=True
    )

    address = models.PositiveIntegerField(
        u'self address of device (id, integer)',
        default=0,
        help_text=u'positive integer',
        blank=False, null=False
    )

    port = models.ForeignKey(
        'ports.Port', verbose_name=u'Port', on_delete=models.SET_NULL, null=True
    )

    type = models.ForeignKey(
        'DeviceType', verbose_name=u'Device type', on_delete=models.SET_NULL, null=True
    )

    record_type = models.IntegerField(
        u'record type (how to store data from device)',
        choices=RecordTypes.get_choices(),
        default=RecordTypes.DONT_RECORD
    )

    comment = models.TextField(
        u'additional comment',
        max_length=1000,
        blank=True, null=True
    )

    class Meta:
        verbose_name = u'device'
        verbose_name_plural = u'devices'
        # unique_together = ('name', 'address')
        # unique_together = ('port', 'address')
        ordering = ['port', 'address', 'name']
        db_table = 'poll_devices'

    def __str__(self):
        return u'{0}:{1}'.format(self.name, self.address)


class DeviceTypeRegister(models.Model):
    u"""
    Register information, specific for some device type
    """

    device_type = models.ForeignKey(
        'DeviceType', verbose_name=u'Device type', on_delete=models.CASCADE
    )

    name = models.CharField(
        u'name of the register',
        max_length=25,
        blank=False, null=False
    )

    address = models.PositiveIntegerField(
        u'address of the current register in devices register map',
        default=0,
        help_text=u'positive integer',
        blank=False, null=False
    )

    function = models.PositiveIntegerField(
        u'read function',
        choices=ReadFunctionCodes.get_choices(),
        default=ReadFunctionCodes.NO_READ
    )

    write_function = models.PositiveIntegerField(
        u'write function',
        choices=WriteFunctionCodes.get_choices(),
        default=WriteFunctionCodes.NO_WRITE
    )

    byte_count = models.PositiveIntegerField(
        u'byte count for register value',
        choices=RegisterDataType.get_choices(),
        default=RegisterDataType.INTEGER,
    )

    comment = models.TextField(
        u'additional comment',
        max_length=1000,
        blank=True, null=True
    )

    class Meta:
        verbose_name = u'register'
        verbose_name_plural = u'registers'
        # unique_together = ('device_type', 'name', 'address')
        unique_together = (('device_type', 'name'), ('device_type', 'address'),)
        ordering = ['device_type', 'name', 'address']
        db_table = 'poll_registers'

    def __str__(self):
        return u'{0} - {1} ({2})'.format(self.device_type.name, self.name, self.address)


class DeviceSchemeLocation(models.Model):
    u"""
    Device scheme location for homepage
    """

    device = models.OneToOneField(
        'devices.Device', verbose_name=u'Device', on_delete=models.CASCADE, null=False
    )

    coordinateX = models.PositiveIntegerField(
        u'X coordinate (location on the scheme in px)',
        default=0,
        help_text=u'positive integer',
        blank=False, null=False
    )

    coordinateY = models.PositiveIntegerField(
        u'Y coordinate (location on the scheme in px)',
        default=0,
        help_text=u'positive integer',
        blank=False, null=False
    )

    class Meta:
        verbose_name = u'device scheme location'
        verbose_name_plural = u'device scheme locations'
        ordering = ['device']
        db_table = 'poll_scheme_locations'

    def __str__(self):
        return u'{0} (X{1}, Y{2})'.format(self.device, self.coordinateX, self.coordinateY)

apps/tasks/models.py
from django.db import models
from apps.common.base_enum import BaseEnumerate


class ErrorReportPlans(BaseEnumerate):
    u"""
    Plans of error reporting
    """

    (
        DONT_REPORT, REPORT_ALL, REPORT_DB, REPORT_LOG
    ) = range(4)

    values = {
        DONT_REPORT: u'Dont report errors',
        REPORT_ALL: u'Report errors in DB and logs',
        REPORT_DB: u'Report errors in DB',
        REPORT_LOG: u'Report errors in logs'
    }


class ReadTaskStatus(BaseEnumerate):
    u"""
    Task status: enabled/disabled
    """

    (
        ENABLED, DISABLED
    ) = range(2)

    values = {
        ENABLED: u'Task is enabled',
        DISABLED: u'Task is disabled'
    }


class WriteTaskStatus(BaseEnumerate):
    u"""
    Task status: enabled/disabled
    """

    (
        ENABLED, DISABLED, SUCCESS, ERROR
    ) = range(4)

    values = {
        ENABLED: u'Task is enabled',
        DISABLED: u'Task is disabled',
        SUCCESS: u'Task has successful result',
        ERROR: u'Task is finished with errors'
    }


class ReadTask(models.Model):
    u"""
    Task to read specific register from some device
    """

    device = models.OneToOneField(
        'devices.Device', verbose_name=u'Device', on_delete=models.CASCADE
    )

    interval = models.PositiveIntegerField(
        u'polling period, s',
        default=60,
        help_text=u'seconds',
        blank=False, null=False
    )

    data_miss_error_report = models.PositiveIntegerField(
        u'report plan on missing data error',
        choices=ErrorReportPlans.get_choices(),
        default=ErrorReportPlans.REPORT_LOG
    )

    status = models.PositiveIntegerField(
        u'task status',
        choices=ReadTaskStatus.get_choices(),
        default=ReadTaskStatus.DISABLED
    )

    class Meta:
        verbose_name = u'read task'
        verbose_name_plural = u'read tasks'
        ordering = ['device']
        db_table = 'poll_read_tasks'

    def __str__(self):
        return u'{0} read task'.format(self.device.name)


class WriteTask(models.Model):
    u"""
    Task to write specific register to some device
    """

    device = models.ForeignKey(
        'devices.Device', verbose_name=u'Device', on_delete=models.CASCADE
    )

    register = models.ForeignKey(
        'devices.DeviceTypeRegister', verbose_name=u'Register', on_delete=models.CASCADE
    )

    value = models.CharField(
        u'value to set to register',
        max_length=20,
        help_text=u'String representation! Be cautious!',
        blank=False, null=False
    )

    status = models.PositiveIntegerField(
        u'task status',
        choices=WriteTaskStatus.get_choices(),
        default=WriteTaskStatus.DISABLED
    )

    changed_datetime = models.DateTimeField(
        u'time point of last modification',
        auto_now=True
    )

    class Meta:
        verbose_name = u'write task'
        verbose_name_plural = u'write tasks'
        ordering = ['device', 'register']
        db_table = 'poll_write_tasks'

    def __str__(self):
        return u'Write task {0} register {1} value {2}'.format(self.device.name, self.register.name, self.value)


class Threshold(models.Model):
    u"""
    Threshold for some device register, used to track by task
    """

    task = models.ForeignKey(
        'ReadTask', verbose_name=u'Task', on_delete=models.CASCADE
    )

    register = models.ForeignKey(
        'devices.DeviceTypeRegister', verbose_name=u'Register', on_delete=models.CASCADE
    )

    # FloatField instead of DecimalField because of firebird problems
    low_threshold = models.FloatField(
        u'low threshold',
        blank=True, null=True
    )

    # FloatField instead of DecimalField because of firebird problems
    high_threshold = models.FloatField(
        u'high threshold',
        blank=True, null=True
    )

    additive = models.FloatField(
        u'additive modifier',
        blank=True, null=True, default=0
    )

    coefficient = models.FloatField(
        u'coefficient modifier',
        blank=True, null=True, default=1
    )

    check_mask = models.PositiveIntegerField(
        u'check logical equality with mask, bool(x & mask), if true => alert',
        help_text=u'positive integer value',
        blank=True, null=True
    )

    mask_explain = models.CharField(
        u'explanation of mask check',
        max_length=30,
        help_text=u'explanation of mask check (for alert message)',
        blank=True, null=True
    )

    threshold_error_report = models.PositiveIntegerField(
        u'report plan on threshold error',
        choices=ErrorReportPlans.get_choices(),
        default=ErrorReportPlans.REPORT_LOG
    )

    class Meta:
        verbose_name = u'threshold'
        verbose_name_plural = u'thresholds'
        # unique_together = ('task', 'register')
        ordering = ['task', 'register']
        db_table = 'poll_thresholds'

    def __str__(self):
        return u'Threshold of {0} register {1}'.format(self.task.device.name, self.register.name)

apps/devices/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Device, DeviceType, DeviceTypeRegister


class DeviceForm(forms.ModelForm):
    def clean_port(self):
        port = self.cleaned_data['port']
        address = self.cleaned_data['address']
        device_exists = Device.objects.filter(port_id=port.id, address=address).exclude(pk=self.instance.pk).exists()
        if not device_exists:
            return port
        else:
            raise ValidationError("Device with this Port and Self address of device (id, integer) already exists.")

    class Meta:
        model = Device
        fields = ['name', 'address', 'port', 'type', 'record_type', 'comment']
        # exclude = ['address']


class DeviceTypeForm(forms.ModelForm):
    class Meta:
        model = DeviceType
        fields = ['name', 'table_name', 'comment']


class DeviceTypeRegisterForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(DeviceTypeRegisterForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance:
            self.fields['device_type'].widget.attrs['hidden'] = True
            self.fields['device_type'].label = ''

    def clean_device_type(self):
        instance = getattr(self, 'instance', None)
        if instance:
            return instance.device_type
        else:
            return self.cleaned_data['device_type']

    class Meta:
        model = DeviceTypeRegister
        fields = ['device_type', 'name', 'address', 'function', 'write_function', 'byte_count', 'comment']

templates/devices/device_detail.html
{% extends "base_site.html" %}
{% block content %}

<div class="page-title-holder d-flex align-items-center">
    <h1 class="page-title">
        {% if device.id %}
            {{ device_title }}
        {% else %}
            New device
        {% endif %}
    </h1>
</div>
<div class="d-flex align-items-start justify-content-between">
    <div class="d-flex col-8">
        <form class="detail-form col-10" action="" method="post">
        {% csrf_token %}
            {% if form.errors %}
            {% for error in form.non_field_errors %}
                <br>
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endfor %}
            {% endif %}
            {% for field in form %}
                {% if field.errors %}
                    <div class="form-group detail-form-group">
                        <label class="">{{ field.label }}</label>
                        <div class="detail-form-control">{{ field }}</div>
                        {% for error in field.errors %}
                            <div class="alert alert-danger" role="alert">
                                {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    <div class="form-group detail-form-group">
                        <label class="form-text">{{ field.label }}</label>
                        <div class="detail-form-control">{{ field }}</div>
                        {% if field.help_text %}
                            <p class="form-text"><small>{{ field.help_text }}</small></p>
                        {% endif %}
                    </div>
                {% endif %}
            {% endfor %}
            <div class="form-group col-8 detail-form-group">
                <button type="submit" class="btn btn-primary" >Save device</button>
                <a class="btn btn-secondary" href="{% url 'devices:devices' %}">Cancel</a>
            </div>
        </form>
    </div>

    <div class="d-flex col-md-4 col-4 align-items-start flex-column">
        <div class="detail-additional-list-title">
            <h2 class="page-title">
                {% if device.readtask %}
                <a href="{% url 'tasks:read_task_detail' device.readtask.id %}">
                    Read Task
                </a>
                {% endif %}
            </h2>
        </div>
        <div class="detail-additional-list-title">
            <h2 class="page-title">
                <a data-toggle="collapse" href="#collapseDetailList" role="button" aria-expanded="false" aria-controls="collapseDetailList">
                    Write tasks <span class="badge badge-light">{{ device.writetask_set.all|length }}</span>
                </a>
            </h2>
        </div>
        <div class="">
            <div class="collapse" id="collapseDetailList">
                <ul class="detail-additional-list">
                {% for task in device.writetask_set.all %}
                    <li class="">
                        <div>
                            <h5>
                                <a href="{% url 'tasks:write_task_detail' task.id %}">{{ task.register.name }} / {{ task.value }}</a>
                            </h5>
                        </div>
                    </li>
                {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extrajs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#navbarNav li').removeClass('active')
        $('#navbarNav li:nth-child(3)').toggleClass('active')

        let elements = document.querySelectorAll('div.detail-form-control > :first-child')
        elements.forEach(el => el.classList.add("form-control"))
    </script>
{% endblock extrajs %}

templates/devices/device_types_list.html
{% extends "base_site.html" %}
{% block content %}

<div class="page-title-holder d-flex align-items-center">
    <h1 class="page-title">Device types <span class="badge badge-light">{{ device_types_list|length }}</span></h1>

    <div class="page-title-controls">
        <a class="btn btn-success" href="{% url 'devices:device_type_detail_new' %}">New device type</a>
    </div>
</div>

<div >
{% if device_types_list %}
    <ul class="objects-list">
    {% for device_type in device_types_list %}
        <li class="objects-row d-flex">
            <div class="object-details d-sm-flex flex-sm-fill align-items-center justify-content-between">
                <div class="d-flex">
                    <div class="d-flex align-items-center object-title">
                        <a href="{% url 'devices:device_type_detail' device_type.id %}">{{ device_type.name }}</a>
                    </div>
                </div>
                <div class="d-flex">
                    <div class="d-flex align-items-center object-title">
                        <a href="{% url 'devices:device_type_registers' device_type.id %}">Registers</a>
                    </div>
                </div>
                <div class="object-description d-flex flex-sm-column align-items-center align-items-sm-start flex-wrap">
                    <p dir="auto">Table: {{ device_type.table_name }}</p>
                    <p dir="auto">Comment: {{ device_type.comment }}</p>
                </div>
                <div class="d-flex align-items-center align-items-sm-end flex-shrink-0 text-secondary objects-list-controls">
                    <a class="btn btn-info" href="{% url 'devices:device_type_detail' device_type.id %}" title="Edit"><i class="fas fa-edit"></i></a>
                    <a>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal" data-id="{{ device_type.id }}" data-name="{{ device_type.name }}" title="Delete">
                            <i class="fas fa-trash-alt"></i>
                        </button>
                    </a>
                </div>
            </div>
        </li>
    {% endfor %}
    </ul>
{% endif %}
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete object alert</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <p>You are going to delete</p>
            <p class="modal-body-detail"></p>
        </div>
        <div class="modal-footer">
            <a class="btn btn-secondary" data-dismiss="modal">Cancel</a>
            <a class="btn btn-primary confirm-delete" href="">Delete</a>
        </div>
        </div>
    </div>
</div>

{% endblock content %}


{% block extrajs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#navbarNav li').removeClass('active')
        $('#navbarNav li:nth-child(3)').toggleClass('active')

        $('#deleteModal').on('show.bs.modal', function (event) {
            let button = $(event.relatedTarget) // Button that triggered the modal
            let object_name = button.data('name') // Extract info from data-* attributes
            let object_id = button.data('id') // Extract info from data-* attributes
            let modal = $(this)
            modal.find('p.modal-body-detail').text(object_name)
            modal.find('a.confirm-delete').attr("href", "{% url 'devices:device_types' %}" + object_id + "/delete/")
        })
    </script>
{% endblock extrajs %}

templates/devices/devices_list.html
{% extends "base_site.html" %}
{% block content %}

<div class="page-title-holder d-flex align-items-center">
    <h1 class="page-title">Devices <span class="badge badge-light">{{ devices_list|length }}</span></h1>

    <div class="page-title-controls">
        <a class="btn btn-success" href="{% url 'devices:device_detail_new' %}">New device</a>
    </div>
</div>

<div >
{% if devices_list %}
    <ul class="objects-list">
    {% for device in devices_list %}
        <li class="objects-row d-flex">
            <div class="object-details d-sm-flex flex-sm-fill align-items-center justify-content-between">
                <div class="d-flex">
                    <div class="d-flex align-items-center object-title">
                        <a href="{% url 'devices:device_detail' device.id %}">{{ device.name }}</a>
                    </div>
                </div>
                <div class="object-description d-flex flex-sm-column">
                    <p dir="auto">
                    {% if device.port %}
                        <a href="{% url 'ports:port_detail' device.port.id %}">{{ device.port }} </a>
                    {% else %}
                        <a href="">Port: None </a>
                    {% endif %}
                      / {{ device.address }}</p>
                    <p dir="auto">
                    {% if device.type %}
                        <a href="{% url 'devices:device_type_detail' device.type.id %}">{{ device.type }}</a>
                    {% else %}
                        <a href="">Device type: None</a>
                    {% endif %}
                    </p>
                </div>
                <div class="object-description d-flex flex-sm-column align-items-center align-items-sm-start flex-wrap">
                    <p dir="auto">Record type: {{ device.record_type }}</p>
                    <p dir="auto">Comment: {{ device.comment }}</p>
                </div>
                <div class="d-flex align-items-center align-items-sm-end flex-shrink-0 text-secondary objects-list-controls">
                    <a class="btn btn-info" href="{% url 'devices:device_detail' device.id %}" title="Edit"><i class="fas fa-edit"></i></a>
                    <a>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal" data-id="{{ device.id }}" data-name="{{ device.name }}" title="Delete">
                            <i class="fas fa-trash-alt"></i>
                        </button>
                    </a>
                </div>
            </div>
        </li>
    {% endfor %}
    </ul>
{% endif %}
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete object alert</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <p>You are going to delete</p>
            <p class="modal-body-detail"></p>
            <p>ALL DEVICE DATA WILL BE DELETED!!!</p>
        </div>
        <div class="modal-footer">
            <a class="btn btn-secondary" data-dismiss="modal">Cancel</a>
            <a class="btn btn-primary confirm-delete" href="">Delete</a>
        </div>
        </div>
    </div>
</div>

{% endblock content %}


{% block extrajs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#navbarNav li').removeClass('active')
        $('#navbarNav li:nth-child(3)').toggleClass('active')

        $('#deleteModal').on('show.bs.modal', function (event) {
            let button = $(event.relatedTarget) // Button that triggered the modal
            let object_name = button.data('name') // Extract info from data-* attributes
            let object_id = button.data('id') // Extract info from data-* attributes
            let modal = $(this)
            modal.find('p.modal-body-detail').text(object_name)
            modal.find('a.confirm-delete').attr("href", "{% url 'devices:devices' %}" + object_id + "/delete/")
        })
    </script>
{% endblock extrajs %}