apps/devices/urls.py
from django.urls import path
from . import views


app_name = 'devices'

urlpatterns = [
    path('devices/', views.devices, name='devices'),
    path('devices/<int:device_id>/', views.device_detail, name='device_detail'),
    path('devices/<int:device_id>/delete/', views.device_delete, name='device_delete'),
    path('devices/new/', views.device_detail, name='device_detail_new'),
    path('devicetypes/', views.device_types, name='device_types'),
    path('devicetypes/<int:device_type_id>/', views.device_type_detail, name='device_type_detail'),
    path('devicetypes/<int:device_type_id>/delete/', views.device_type_delete, name='device_type_delete'),
    path('devicetypes/new/', views.device_type_detail, name='device_type_detail_new'),
    path('devicetypes/<int:device_type_id>/registers/', views.device_type_registers, name='device_type_registers'),
    path('devicetypes/<int:device_type_id>/registers/<int:register_id>/', views.device_type_register_detail,
         name='device_type_register_detail'),
    path('devicetypes/<int:device_type_id>/registers/<int:register_id>/delete/', views.device_type_register_delete,
         name='device_type_register_delete'),
    path('devicetypes/<int:device_type_id>/registers/new/', views.device_type_register_detail,
         name='device_type_register_detail_new'),
    path('devices/<int:device_id>/registers/', views.device_registers,
         name='device_registers'),
]

apps/tasks/urls.py
from django.urls import path
from . import views


app_name = 'tasks'

urlpatterns = [
    path('readtasks/', views.read_tasks, name='read_tasks'),
    path('readtasks/<int:task_id>/', views.read_task_detail, name='read_task_detail'),
    path('readtasks/<int:task_id>/delete/', views.read_task_delete, name='read_task_delete'),
    path('readtasks/new/', views.read_task_detail, name='read_task_detail_new'),
    path('readtasks/<int:task_id>/thresholds/', views.task_thresholds, name='task_thresholds'),
    path('readtasks/<int:task_id>/thresholds/<int:threshold_id>/', views.task_threshold_detail,
         name='task_threshold_detail'),
    path('readtasks/<int:task_id>/thresholds/<int:threshold_id>/delete/', views.task_threshold_delete,
         name='task_threshold_delete'),
    path('readtasks/<int:task_id>/thresholds/new/', views.task_threshold_detail, name='task_threshold_detail_new'),
    path('writetasks/', views.write_tasks, name='write_tasks'),
    path('writetasks/<int:task_id>/', views.write_task_detail, name='write_task_detail'),
    path('writetasks/<int:task_id>/delete/', views.write_task_delete, name='write_task_delete'),
    path('writetasks/new/', views.write_task_detail, name='write_task_detail_new'),

    path('readtasks/<int:task_id>/toggle/', views.read_task_toggle, name='read_task_toggle'),
    path('writetasks/<int:task_id>/toggle/', views.write_task_toggle, name='write_task_toggle'),
]

modbus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('devices/', include('apps.devices.urls')),
]

urlpatterns += [
    path('', include('apps.ports.urls')),
]

urlpatterns += [
    path('tasks/', include('apps.tasks.urls')),
]

urlpatterns += [
    path('', include('apps.devicedata.urls')),
]

urlpatterns += [
    path('', views.main, name='main'),
    path('devices_scheme/filtered', views.filter_devices_scheme, name='filter_devices_scheme'),
    path('devices_scheme/update', views.update_devices_scheme, name='update_devices_scheme'),
    path('errors/list', views.errors_list, name='errors_list'),
]

urlpatterns += [
    path('', RedirectView.as_view(url='/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/tasks/models.py
from django.db import models
from apps.common.base_enum import BaseEnumerate


class ErrorReportPlans(BaseEnumerate):
    u"""
    Plans of error reporting
    """

    (
        DONT_REPORT, REPORT_ALL, REPORT_DB, REPORT_LOG
    ) = range(4)

    values = {
        DONT_REPORT: u'Dont report errors',
        REPORT_ALL: u'Report errors in DB and logs',
        REPORT_DB: u'Report errors in DB',
        REPORT_LOG: u'Report errors in logs'
    }


class ReadTaskStatus(BaseEnumerate):
    u"""
    Task status: enabled/disabled
    """

    (
        ENABLED, DISABLED
    ) = range(2)

    values = {
        ENABLED: u'Task is enabled',
        DISABLED: u'Task is disabled'
    }


class WriteTaskStatus(BaseEnumerate):
    u"""
    Task status: enabled/disabled
    """

    (
        ENABLED, DISABLED, SUCCESS, ERROR
    ) = range(4)

    values = {
        ENABLED: u'Task is enabled',
        DISABLED: u'Task is disabled',
        SUCCESS: u'Task has successful result',
        ERROR: u'Task is finished with errors'
    }


class ReadTask(models.Model):
    u"""
    Task to read specific register from some device
    """

    device = models.OneToOneField(
        'devices.Device', verbose_name=u'Device', on_delete=models.CASCADE
    )

    interval = models.PositiveIntegerField(
        u'polling period, s',
        default=60,
        help_text=u'seconds',
        blank=False, null=False
    )

    data_miss_error_report = models.PositiveIntegerField(
        u'report plan on missing data error',
        choices=ErrorReportPlans.get_choices(),
        default=ErrorReportPlans.REPORT_LOG
    )

    status = models.PositiveIntegerField(
        u'task status',
        choices=ReadTaskStatus.get_choices(),
        default=ReadTaskStatus.DISABLED
    )

    class Meta:
        verbose_name = u'read task'
        verbose_name_plural = u'read tasks'
        ordering = ['device']
        db_table = 'poll_read_tasks'

    def __str__(self):
        return u'{0} read task'.format(self.device.name)


class WriteTask(models.Model):
    u"""
    Task to write specific register to some device
    """

    device = models.ForeignKey(
        'devices.Device', verbose_name=u'Device', on_delete=models.CASCADE
    )

    register = models.ForeignKey(
        'devices.DeviceTypeRegister', verbose_name=u'Register', on_delete=models.CASCADE
    )

    value = models.CharField(
        u'value to set to register',
        max_length=20,
        help_text=u'String representation! Be cautious!',
        blank=False, null=False
    )

    status = models.PositiveIntegerField(
        u'task status',
        choices=WriteTaskStatus.get_choices(),
        default=WriteTaskStatus.DISABLED
    )

    changed_datetime = models.DateTimeField(
        u'time point of last modification',
        auto_now=True
    )

    class Meta:
        verbose_name = u'write task'
        verbose_name_plural = u'write tasks'
        ordering = ['device', 'register']
        db_table = 'poll_write_tasks'

    def __str__(self):
        return u'Write task {0} register {1} value {2}'.format(self.device.name, self.register.name, self.value)


class Threshold(models.Model):
    u"""
    Threshold for some device register, used to track by task
    """

    task = models.ForeignKey(
        'ReadTask', verbose_name=u'Task', on_delete=models.CASCADE
    )

    register = models.ForeignKey(
        'devices.DeviceTypeRegister', verbose_name=u'Register', on_delete=models.CASCADE
    )

    # FloatField instead of DecimalField because of firebird problems
    low_threshold = models.FloatField(
        u'low threshold',
        blank=True, null=True
    )

    # FloatField instead of DecimalField because of firebird problems
    high_threshold = models.FloatField(
        u'high threshold',
        blank=True, null=True
    )

    additive = models.FloatField(
        u'additive modifier',
        blank=True, null=True, default=0
    )

    coefficient = models.FloatField(
        u'coefficient modifier',
        blank=True, null=True, default=1
    )

    check_mask = models.PositiveIntegerField(
        u'check logical equality with mask, bool(x & mask), if true => alert',
        help_text=u'positive integer value',
        blank=True, null=True
    )

    mask_explain = models.CharField(
        u'explanation of mask check',
        max_length=30,
        help_text=u'explanation of mask check (for alert message)',
        blank=True, null=True
    )

    threshold_error_report = models.PositiveIntegerField(
        u'report plan on threshold error',
        choices=ErrorReportPlans.get_choices(),
        default=ErrorReportPlans.REPORT_LOG
    )

    class Meta:
        verbose_name = u'threshold'
        verbose_name_plural = u'thresholds'
        # unique_together = ('task', 'register')
        ordering = ['task', 'register']
        db_table = 'poll_thresholds'

    def __str__(self):
        return u'Threshold of {0} register {1}'.format(self.task.device.name, self.register.name)

apps/tasks/forms.py
from django import forms
from django.core.exceptions import ValidationError

from apps.devices.models import DeviceTypeRegister
from .models import ReadTask, WriteTask, Threshold


class ReadTaskForm(forms.ModelForm):
    class Meta:
        model = ReadTask
        fields = ['device', 'interval', 'data_miss_error_report', 'status']


class WriteTaskForm(forms.ModelForm):
    def clean(self):
        cleaned_data = super().clean()
        device = cleaned_data.get("device")
        register = cleaned_data.get("register")

        if device and register:
            if len(list(DeviceTypeRegister.objects.filter(device_type__device__id=device.id, id=register.id))) == 0:
                raise ValidationError('Register does not belong to this device')

    class Meta:
        model = WriteTask
        fields = ['device', 'register', 'value', 'status']
        exclude = ['changed_datetime']


class ThresholdForm(forms.ModelForm):
    # register = forms.ModelChoiceField(queryset=None)

    def __init__(self, *args, **kwargs):
        super(ThresholdForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance:
            self.fields['task'].widget.attrs['hidden'] = True
            self.fields['task'].label = ''
            # self.fields['register'].queryset = DeviceTypeRegister.objects.all()

    def clean_device_type(self):
        instance = getattr(self, 'instance', None)
        if instance:
            return instance.task
        else:
            return self.cleaned_data['task']

    def clean(self):
        cleaned_data = super().clean()
        task = cleaned_data.get("task")
        register = cleaned_data.get("register")

        if task and register:
            if len(list(DeviceTypeRegister.objects.filter(device_type__device__id=task.device.id, id=register.id))) == 0:
                raise ValidationError('Register does not belong to this device')

    class Meta:
        model = Threshold
        fields = ['task', 'register', 'low_threshold', 'high_threshold', 'additive', 'coefficient', 'check_mask',
                  'mask_explain', 'threshold_error_report']

templates/tasks/read_tasks_list.html
{% extends "base_site.html" %}
{% block content %}

<div class="page-title-holder d-flex align-items-center">
    <h1 class="page-title">Read tasks <span class="badge badge-light">{{ tasks_list|length }}</span></h1>

    <div class="page-title-controls">
        <a class="btn btn-success" href="{% url 'tasks:read_task_detail_new' %}">New read task</a>
    </div>
</div>

<div >
{% if tasks_list %}
    <ul class="objects-list">
    {% for task in tasks_list %}
        <li class="objects-row d-flex">
            <div class="object-details d-sm-flex flex-sm-fill align-items-center justify-content-between">
                <div class="d-flex">
                    <div class="d-flex align-items-center object-title">
                        <a href="{% url 'tasks:read_task_detail' task.id %}">{{ task.device.name }} task</a>
                    </div>
                </div>
                <div class="d-flex">
                    <div class="d-flex align-items-center object-title">
                        <a href="{% url 'tasks:task_thresholds' task.id %}">Thresholds</a>
                    </div>
                </div>
                <div class="object-description d-flex flex-sm-column align-items-center align-items-sm-start flex-wrap">
                    <a>
                        {% if task.status %}
                        <button type="button" class="task-status btn btn-outline-primary disabled" data-id="{{ task.id }}" title="Status">
                            {{ task.status_str }}
                        </button>
                        {% else %}
                        <button type="button" class="task-status btn btn-primary" data-id="{{ task.id }}" title="Status">
                            {{ task.status_str }}
                        </button>
                        {% endif %}
                    </a>
                </div>
                <div class="object-description d-flex flex-sm-column align-items-center align-items-sm-start flex-wrap">
                    <p dir="auto">Interval: {{ task.interval }} (s)</p>
                    <p dir="auto">Error plan: {{ task.data_miss_error_report }}</p>
                </div>
                <div class="d-flex align-items-center align-items-sm-end flex-shrink-0 text-secondary objects-list-controls">
                    <a class="btn btn-info" href="{% url 'tasks:read_task_detail' task.id %}" title="Edit"><i class="fas fa-edit"></i></a>
                    <a>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal" data-id="{{ task.id }}" data-name="{{ task.device.name }} task" title="Delete">
                            <i class="fas fa-trash-alt"></i>
                        </button>
                    </a>
                </div>
            </div>
        </li>
    {% endfor %}
    </ul>
{% endif %}
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete object alert</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <p>You are going to delete</p>
            <p class="modal-body-detail"></p>
        </div>
        <div class="modal-footer">
            <a class="btn btn-secondary" data-dismiss="modal">Cancel</a>
            <a class="btn btn-primary confirm-delete" href="">Delete</a>
        </div>
        </div>
    </div>
</div>

{% endblock content %}


{% block extrajs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#navbarNav li').removeClass('active')
        $('#navbarNav li:nth-child(5)').toggleClass('active')

        $('#deleteModal').on('show.bs.modal', function (event) {
            let button = $(event.relatedTarget) // Button that triggered the modal
            let object_name = button.data('name') // Extract info from data-* attributes
            let object_id = button.data('id') // Extract info from data-* attributes
            let modal = $(this)
            modal.find('p.modal-body-detail').text(object_name)
            modal.find('a.confirm-delete').attr("href", "{% url 'tasks:read_tasks' %}" + object_id + "/delete/")
        })

        $('button.task-status').on('click', function(event) {
            let button = $(event.currentTarget)
            let object_id = button.data('id')
            $.getJSON("{% url 'tasks:read_tasks' %}" + object_id + "/toggle/", function(data) {
                if (data['changed']) {
                    button.text(data['task_status'])
                    button.toggleClass('btn-outline-primary')
                    button.toggleClass('btn-primary')
                    button.toggleClass('disabled')
                }
            })
        })
    </script>
{% endblock extrajs %}

templates/tasks/threshold_detail.html
{% extends "base_site.html" %}
{% block content %}

<div class="page-title-holder d-flex align-items-center">
    <h1 class="page-title">
        <a href="{% url 'devices:device_detail' threshold.task.device.id %}">{{ threshold.task.device }} </a>
        <a href="{% url 'tasks:read_task_detail' threshold.task.id %}"> task </a>
        {% if threshold.id %}
            {{ threshold_title }} threshold
        {% else %}
            new threshold
        {% endif %}
    </h1>
</div>
<div class="d-flex align-items-start justify-content-between">
    <div class="d-flex col-8">
        <form class="detail-form col-10" action="" method="post">
        {% csrf_token %}
            {% if form.errors %}
            {% for error in form.non_field_errors %}
                <br>
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endfor %}
            {% endif %}
            {% for field in form %}
                {% if field.errors %}
                    <div class="form-group detail-form-group">
                        <label class="">{{ field.label }}</label>
                        <div class="detail-form-control">{{ field }}</div>
                        {% for error in field.errors %}
                            <div class="alert alert-danger" role="alert">
                                {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    <div class="form-group detail-form-group">
                        <label class="form-text">{{ field.label }}</label>
                        <div class="detail-form-control">{{ field }}</div>
                        {% if field.help_text %}
                            <p class="form-text"><small>{{ field.help_text }}</small></p>
                        {% endif %}
                    </div>
                {% endif %}
            {% endfor %}
            <div class="form-group col-8 detail-form-group">
                <button type="submit" class="btn btn-primary" >Save threshold</button>
                <a class="btn btn-secondary" href="{% url 'tasks:task_thresholds' threshold.task.id %}">Cancel</a>
            </div>
        </form>
    </div>

    <div class="d-flex col-md-4 col-4 align-items-start flex-column">
        <div class="detail-additional-list-title">
            <h2 class="page-title">
                <a data-toggle="collapse" href="#collapseDetailList" role="button" aria-expanded="false" aria-controls="collapseDetailList">
                    Last Errors <span class="badge badge-light">0</span>
                </a>
            </h2>
        </div>
        <div class="">
            <div class="collapse" id="collapseDetailList">
                <ul class="detail-additional-list">
{#                {% for task in device.writetask_set.all %}#}
{#                    <li class="">#}
{#                        <div>#}
{#                            <h5>#}
{#                                <a href="#{{ task.id }}">{{ task.register.name }} / {{ task.value }}</a>#}
{#                            </h5>#}
{#                        </div>#}
{#                    </li>#}
{#                {% endfor %}#}
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block extrajs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#navbarNav li').removeClass('active')
        $('#navbarNav li:nth-child(5)').toggleClass('active')

        let elements = document.querySelectorAll('div.detail-form-control > :first-child')
        elements.forEach(el => el.classList.add("form-control"))

        $('form').onload = getRegisters()

        function getRegisters() {
            let device_id = {{ threshold.task.device.id }}
            if (!device_id) {
                device_id = 0
            }
            // get registers of device type and edit select of register
            $.getJSON("{% url 'devices:devices' %}" + device_id + "/registers/", function(data) {
                let active_option_value = document.querySelector('#id_register option:checked').getAttribute("value")
                let registers_select = document.querySelector('#id_register')
                registers_select.innerHTML = ''
                let option = document.createElement("option")
                option.innerHTML = "---------"
                option.setAttribute("value", '')
                registers_select.appendChild(option)

                if (data['registers']) {
                    data['registers'].forEach((currentValue) => {
                        if (currentValue['r_function']) {
                            let option = document.createElement("option")
                            option.setAttribute("value", currentValue['id'])
                            option.innerHTML = currentValue['value']
                            registers_select.appendChild(option)
                        }
                    })
                }

                if (active_option_value) {
                    let active_option = document.querySelector('#id_register option[value="' + active_option_value + '"]')
                    if (active_option) {
                        active_option.setAttribute("selected", '')
                    }
                }
            })
        }

    </script>
{% endblock extrajs %}

templates/tasks/thresholds_list.html
{% extends "base_site.html" %}
{% block content %}

<div class="page-title-holder d-flex align-items-center">
    <h1 class="page-title"><a href="{% url 'tasks:read_task_detail' task.id %}">{{ task }}</a> thresholds <span class="badge badge-light">{{ thresholds_list|length }}</span></h1>

    <div class="page-title-controls">
        <a class="btn btn-success" href="{% url 'tasks:task_threshold_detail_new' task.id %}">New threshold</a>
    </div>
</div>

<div >
{% if thresholds_list %}
    <ul class="objects-list">
    {% for threshold in thresholds_list %}
        <li class="objects-row d-flex">
            <div class="object-details d-sm-flex flex-sm-fill align-items-center justify-content-between">
                <div class="d-flex">
                    <div class="d-flex align-items-center object-title">
                        <a href="{% url 'tasks:task_threshold_detail' task.id threshold.id %}">{{ threshold.register }} threshold</a>
                    </div>
                </div>
                <div class="object-description d-flex flex-sm-column align-items-end align-items-sm-start flex-wrap">
                    <p dir="auto">Low threshold: <strong>{{ threshold.low_threshold }}</strong></p>
                    <p dir="auto">High threshold: <strong>{{ threshold.high_threshold }}</strong></p>
                </div>
                <div class="object-description d-flex flex-sm-column align-items-end align-items-sm-start flex-wrap">
                    <p dir="auto">Additive: <strong>{{ threshold.additive }}</strong></p>
                    <p dir="auto">Coefficient: <strong>{{ threshold.coefficient }}</strong></p>
                </div>
                <div class="object-description d-flex flex-sm-column align-items-end align-items-sm-start flex-wrap">
                    <p dir="auto">Mask: <strong>{{ threshold.check_mask }}</strong></p>
                    <p dir="auto">Mask detail: <strong>{{ threshold.mask_explain }}</strong></p>
                    <p dir="auto">Error plan: <strong>{{ threshold.threshold_error_report }}</strong></p>
                </div>
                <div class="d-flex align-items-center align-items-sm-end flex-shrink-0 text-secondary objects-list-controls">
                    <a class="btn btn-info" href="{% url 'tasks:task_threshold_detail' task.id threshold.id %}" title="Edit"><i class="fas fa-edit"></i></a>
                    <a>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal" data-id="{{ threshold.id }}" data-name="{{ threshold.register }} threshold" title="Delete">
                            <i class="fas fa-trash-alt"></i>
                        </button>
                    </a>
                </div>
            </div>
        </li>
    {% endfor %}
    </ul>
{% endif %}
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete object alert</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <p>You are going to delete</p>
            <p class="modal-body-detail"></p>
        </div>
        <div class="modal-footer">
            <a class="btn btn-secondary" data-dismiss="modal">Cancel</a>
            <a class="btn btn-primary confirm-delete" href="">Delete</a>
        </div>
        </div>
    </div>
</div>

{% endblock content %}


{% block extrajs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#navbarNav li').removeClass('active')
        $('#navbarNav li:nth-child(5)').toggleClass('active')

        $('#deleteModal').on('show.bs.modal', function (event) {
            let button = $(event.relatedTarget) // Button that triggered the modal
            let object_name = button.data('name') // Extract info from data-* attributes
            let object_id = button.data('id') // Extract info from data-* attributes
            let modal = $(this)
            modal.find('p.modal-body-detail').text(object_name)
            modal.find('a.confirm-delete').attr("href", "{% url 'tasks:task_thresholds' task.id %}" + object_id + "/delete/")
        })
    </script>
{% endblock extrajs %}

templates/tasks/write_task_detail.html
{% extends "base_site.html" %}
{% block content %}

<div class="page-title-holder d-flex align-items-center">
    <h1 class="page-title">
        {% if task.id %}
            {{ task_title }} task
        {% else %}
            New write task
        {% endif %}
    </h1>
</div>
<div class="d-flex align-items-start justify-content-between">
    <div class="d-flex col-8">
        <form class="detail-form col-10" action="" method="post">
        {% csrf_token %}
            {% if form.errors %}
            {% for error in form.non_field_errors %}
                <br>
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endfor %}
            {% endif %}
            {% for field in form %}
                {% if field.errors %}
                    <div class="form-group detail-form-group">
                        <label class="">{{ field.label }}</label>
                        <div class="detail-form-control">{{ field }}</div>
                        {% for error in field.errors %}
                            <div class="alert alert-danger" role="alert">
                                {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    <div class="form-group detail-form-group">
                        <label class="form-text">{{ field.label }}</label>
                        <div class="detail-form-control">{{ field }}</div>
                        {% if field.help_text %}
                            <p class="form-text"><small>{{ field.help_text }}</small></p>
                        {% endif %}
                    </div>
                {% endif %}
            {% endfor %}
            <div class="form-group col-8 detail-form-group">
                <button type="submit" class="btn btn-primary" >Save task</button>
                <a class="btn btn-secondary" href="{% url 'tasks:write_tasks' %}">Cancel</a>
            </div>
        </form>
    </div>

    <div class="d-flex col-md-4 col-4 align-items-start flex-column">
        <div class="detail-additional-list-title">
            <h2 class="page-title">
                {% if task.device %}
                <a href="{% url 'devices:device_detail' task.device.id %}">
                    Device {{ task.device.name }}
                </a>
                {% else %}
                {% endif %}
            </h2>
        </div>
    </div>
</div>
{% endblock content %}

{% block extrajs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#navbarNav li').removeClass('active')
        $('#navbarNav li:nth-child(5)').toggleClass('active')

        let elements = document.querySelectorAll('div.detail-form-control > :first-child')
        elements.forEach(el => el.classList.add("form-control"))

        $('#id_device').on('change', getRegisters)
        $('form').onload = getRegisters()


        function getRegisters() {
            let device_id = document.querySelector('#id_device option:checked').getAttribute("value")
            if (!device_id) {
                device_id = 0
            }
            // get registers of device type and edit select of register
            $.getJSON("{% url 'devices:devices' %}" + device_id + "/registers/", function(data) {
                let active_option_value = document.querySelector('#id_register option:checked').getAttribute("value")
                let registers_select = document.querySelector('#id_register')
                registers_select.innerHTML = ''
                let option = document.createElement("option")
                option.innerHTML = "---------"
                option.setAttribute("value", '')
                registers_select.appendChild(option)

                if (data['registers']) {
                    data['registers'].forEach((currentValue) => {
                        if (currentValue['w_function']) {
                            let option = document.createElement("option")
                            option.setAttribute("value", currentValue['id'])
                            option.innerHTML = currentValue['value']
                            registers_select.appendChild(option)
                        }
                    })
                }

                if (active_option_value) {
                    let active_option = document.querySelector('#id_register option[value="' + active_option_value + '"]')
                    if (active_option) {
                        active_option.setAttribute("selected", '')
                    }
                }
            })
        }
    </script>
{% endblock extrajs %}